name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Node.js and pnpm
        uses: ./.github/common/setup-node-pnpm

      - name: Run ESLint
        run: pnpm run lint:check

  tsc:
    name: tsc
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Node.js and pnpm
        uses: ./.github/common/setup-node-pnpm

      - name: Run tsc
        run: pnpm run typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Node.js and pnpm
        uses: ./.github/common/setup-node-pnpm

      - name: Run Prettier
        run: pnpm run format:check
